### ISSUE TITLE
HID USB device note ready

### ISSUE THREAD

**Issue by ripunk** [urbanadventurer/Android-PIN-Bruteforce#1]
how fix this

![Screenshot_2020-10-27-12-33-23-740_com gbwhatsapp](https://user-images.githubusercontent.com/30873947/97266363-eb601d00-185a-11eb-9c1e-5f676252fca1.jpg)

**Comment by urbanadventurer** [comment]
Did you get this working?

This error could be caused by the OTG cable being plugged into the NetHunter phone instead of the locked phone.

Did you try using `./android-pin-bruteforce diag` to get diagnostic information?

**Comment by ripunk** [comment]
![Screenshot_20201028-113837](https://user-images.githubusercontent.com/30873947/97391638-40ab3580-1912-11eb-8b82-ef622e631335.png)
Like this sir?

**Comment by ripunk** [comment]
![Screenshot_20201028-114339](https://user-images.githubusercontent.com/30873947/97391889-e2328700-1912-11eb-9892-9947b014bc6e.png)

Thx work sir 🤩🤩🤩

**Comment by urbanadventurer** [comment]
I'm pleased to learn you got it working 😎
