### ISSUE TITLE
Script is not sending PIN to connected Samsung Phone

### ISSUE THREAD

**Issue by rmnrgb** [urbanadventurer/Android-PIN-Bruteforce#106]
Hi,

Please see the below screenshot - I do not see PIN entering on the Samsung Phone.

![image](https://user-images.githubusercontent.com/97467476/148811027-efb4d113-a464-41d4-b059-bb0ac192519f.png)

I have connected a USB Keyboard to the phone which is working! Please help!

Thanks,

**Comment by urbanadventurer** [comment]
Something is wrong with the USB connection.
