### ISSUE TITLE
How can i fix this?

### ISSUE THREAD

**Issue by Muskaaaa** [urbanadventurer/Android-PIN-Bruteforce#113]
Hello!
Can you help me to fix this please?
It writes:
Android PIN brute-force :: version 0.1
[INFO] Loading optimised PIN list for 6 digits (optimised-pin-length-6.txt)
[INFO] PIN list contains 1000000 PINs
[INFO] Checking environment
[FAIL] HID device (/dev/hidg0) not found
$ android-pin-bruteforce diag
android-pin-bruteforce: command not found
$ bash ./android-pin-bruteforce diag
Android PIN brute-force :: version 0.1
[INFO] # Diagnostic info
[FAIL] HID device (/dev/hidg0) not found
[FAIL] hid-keyboard executable (/system/xbin/hid-keyboard) not found
[FAIL] usb-devices executable (/usr/bin/usb-devices) not found
[INFO] ## Executing Command: /usr/bin/usb-devices
./android-pin-bruteforce: line 151: /usr/bin/usb-devices: No such file or directory
[FAIL] usb-devices script failed. Return code 127.
[INFO] ## Finding Android Phone USB Device
./android-pin-bruteforce: line 161: /usr/bin/usb-devices: No such file or directory
[INFO] Expected result, no device found.
[INFO] ## Sending Enter Key
./android-pin-bruteforce: line 170: /system/xbin/hid-keyboard: Permission denied
[FAIL] Key failed to send. Return code 126.
[INFO] ## Executing Command: /system/bin/getprop |grep usb
[init.svc.usbd]: [stopped]
[miui.usb.dialog]: [1]
[persist.data.df.dev_name]: [rmnet_usb0]
[persist.sys.usb.config]: [none]
[persist.sys.usb.qmmi.func]: [none]
[ro.boot.usbcontroller]: [a600000.dwc3]
[ro.vendor.audio.soundfx.usb]: [true]
[sys.usb.config]: [mtp]
[sys.usb.configfs]: [1]
[sys.usb.controller]: [a600000.dwc3]
[sys.usb.mtp.device_type]: [3]
[sys.usb.state]: [mtp]
[vendor.audio.feature.usb_offload.enable]: [true]
[vendor.audio.feature.usb_offload_burst_mode.enable]: [true]
[vendor.audio.feature.usb_offload_sidetone_volume.enable]: [false]
[vendor.audio.usb.disable.sidetone]: [true]

[INFO] ## Executing Command: dmesg | grep -i usb | tail

[INFO] # Troubleshooting tips
- Check the NetHunter phone is succesfully emulating a keyboard by connecting it to a computer with a regular charging/data USB cable. Open a text editor like Notepad and you should see it sending PINs. Note that you do not need an OTG cable for this.
- Check the Nethunter phone has a regular USB cable attached, and the locked phone has an OTG adaptor attached.
- Try using different cables/adaptors. You may have a faulty cable/adaptor.
- Perform a hard reset of both phones by holding down the power button for 20 seconds.
- Try this command: /system/bin/setprop sys.usb.config hid
Everything is failed

**Comment by urbanadventurer** [comment]
Thanks for the full output.

What type of phone are you using?
