### ISSUE TITLE
Does Not Work Xiaomi Note 5A

### ISSUE THREAD

**Issue by snoozedesert** [urbanadventurer/Android-PIN-Bruteforce#13]
I have Error Message :
 $ bash ./android-pin-bruteforce --length 4
Android PIN brute-force :: version 0.1
[INFO] Loading optimised PIN list for 4 digits (optimised-pin-length-4.txt)
[INFO] PIN list contains 10001 PINs
[INFO] Checking environment
[FAIL] HID device (/dev/hidg0) not found

**Comment by urbanadventurer** [comment]
Try using the script with Kali Nethunter on your Android phone.
