### ISSUE TITLE
HID USB device Not Ready

### ISSUE THREAD

**Issue by Abkasem** [urbanadventurer/Android-PIN-Bruteforce#131]
# Describe the bug

**To Reproduce**

**Expected behavior**

**Screenshots**
![Uploading Screenshot_٢٠٢٣٠٢١٨-٢١٤٨١٩.jpg…]()

**Comment by Abkasem** [comment]
#
![Screenshot_٢٠٢٣٠٢١٨-٢١٤٨٠٧](https://user-images.githubusercontent.com/125785636/219934969-36ea70d4-0ccf-4ae0-a566-708d592203b4.jpg)

**Comment by urbanadventurer** [comment]
I had this problem myself. It is usually solved by rebooting devices and unplugging and replugging devices.
