### ISSUE TITLE
Hid device 

### ISSUE THREAD

**Issue by Wasniksujall** [urbanadventurer/Android-PIN-Bruteforce#135]
Android PIN brute-force :: version 0.2
[INFO] Loading optimised PIN list for 3 digits (optimised-pin-length-3.txt)
[INFO] PIN list contains 1000 PINs
[INFO] Checking environment
[FAIL] HID device (/dev/hidg0) not found# Describe the bug

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by urbanadventurer** [comment]
Duplicate of #132
