### ISSUE TITLE
Locked phone: XXX, Nethunter phone: XXX - Bug description

### ISSUE THREAD

**Issue by T935433** [urbanadventurer/Android-PIN-Bruteforce#140]
Svp j'ai un samsung s9+ qui n'a pas la fonction hid usb
Que faire

**Comment by urbanadventurer** [comment]
Is the Samsung 9+ the locked phone or the attacking phone?

**Comment by T935433** [comment]
> Le Samsung 9+ est-il le téléphone verrouillé ou le téléphone attaquant ?

the attacking phone

**Comment by muthumanika8** [comment]
Hi

**Comment by T935433** [comment]
> Salut

Hi

**Comment by urbanadventurer** [comment]
Duplicate of #132
