### ISSUE TITLE
[FAIL] HID device (/dev/hidg0) not found

### ISSUE THREAD

**Issue by Ricca665** [urbanadventurer/Android-PIN-Bruteforce#142]
# Describe the bug
Cannot find '/dev/hidg0' even if my kernel supports Emulating a keyboard (Tested with rucky)

**To Reproduce**
1. Run 'bash ./android-pin-bruteforce crack' in termux
2. Thats it

**Expected behavior**
To run

**Screenshots**

Here's what happens:
Android PIN brute-force :: version 0.2
[INFO] PIN list contains 1000 PINs
[INFO] Checking environment
[FAIL] HID device (/dev/hidg0) not found

**Comment by urbanadventurer** [comment]
Can you find out what device Rucky is using?

The `lsof` command could help with this. Something like `lsof | grep rucky | grep dev` may give you the correct device in /dev/ to use.

**Comment by urbanadventurer** [comment]
This is a tool to enable USB gadgets. https://f-droid.org/en/packages/net.tjado.usbgadget/
Can you let me know if this helps?

**Comment by Rh0alex** [comment]
I got the same problem here, I still can't solve it

**Comment by TillZxx** [comment]
Have the same problme. Some solutions so far?

**Comment by madhavswami** [comment]
Bro any more solutionnn you can give a video tutorial

**Comment by SeifAjax04** [comment]
same issue!

**Comment by urbanadventurer** [comment]
I assume you checked for /dev/hidg1?

**Comment by bangkokhermetik** [comment]
Same issue here , i think i have to Root my phone first but i'm not sure, i even can't do a sudo or a tsu, i thought it was more easy to fill my flipper zero from termux but anyway we are here to try, no!? By the way thank you for your work

**Comment by urbanadventurer** [comment]
You have to root your phone to crack with. The locked phone doesn't need to be rooted.

**Comment by bangkokhermetik** [comment]
Thank you for your advice
