### ISSUE TITLE
hid-keyboard: cannot execute: required file not found.

### ISSUE THREAD

**Issue by sub-arctic** [urbanadventurer/Android-PIN-Bruteforce#146]
# Describe the bug
I have read through many similar issues about the hid-keyboard binary. For me, the /system/xbin directory did not have the correct binary, so I copied it to /usr/bin (from kali-chroot) as the /system directory was read only for me (Evolution X on Veux). I changed the config to reflect the location of the script, but when I run either the main bruteforce script, or the hid-keyboard script itself, it always returns the same error: `bash: /usr/bin/hid-keyboard: cannot execute: required file not found`. I have no idea which file it is missing, and for good measure I copied all the files from `/data/data/com.offsec.nethunter/files/scripts/bin/` to the same directory as the script, so I'm not sure what is wrong. I even copied the `su` binary to the same directory, with no luck. The hid0 and hid1 devices are operational, as set through the NetHunter USB Arsenal. I know it isn't a problem with this project, but just the hid-keyboard binary it depends on. Is there any way to satisfy the binary?

**To Reproduce**
1. Run copied `hid-keyboard` binary from anywhere in the kali-chroot, or run `android-hid-bruteforce diag` and see the same result.
2. Error

**Expected behavior**
Expected script and binary to run as normal.

**Comment by Raito00** [comment]
The same problem ...

**Comment by urbanadventurer** [comment]
You could try compiling it yourself, e.g. from here https://www.kernel.org/doc/html/latest/usb/gadget_hid.html and there's more info in the README.
