### ISSUE TITLE
Problems with nethunter rootless

### ISSUE THREAD

**Issue by ali655377** [urbanadventurer/Android-PIN-Bruteforce#147]
# Describe the bug
When i execute the command ./android-pin-Bruteforce
It errors and will say
[FAIL] HID device (/dev/hidg0) not found
[FAIL] hid-keyboard executable (/system/xbin/hid-keyboard) not found
[FAIL] usb-devices executable (/usr/bin/usb-devices) not found(nh phone is poco x4 pro stock miui global rootless if anyone is wondering)

**To Reproduce**
1. Execute command 
2. See error

**Expected behavior**
Pin bruteforce start

**Screenshots**
![Screenshot_2023-10-05-14-48-00-833_com termux](https://github.com/urbanadventurer/Android-PIN-Bruteforce/assets/79049208/3d81c536-ed46-4b43-ada6-417f589509f0)
![Screenshot_2023-10-05-14-49-56-598_com termux](https://github.com/urbanadventurer/Android-PIN-Bruteforce/assets/79049208/884682e2-5835-4aa7-b09f-a6c1fe9080ff)

**Comment by urbanadventurer** [comment]
As your phone is `poco x4 pro stock miui global rootless` you will need to install the dependencies yourself.
