### ISSUE TITLE
hid-keyboard works with computer but not with phone (HID USB device not ready)

### ISSUE THREAD

**Issue by simtcrom** [urbanadventurer/Android-PIN-Bruteforce#19]
I went through couple of issues listed here and my initials issues are sorted out.
Now when I connect to computer and kept a notepad open and when executed **_bash ./android-pin-bruteforce crack_** I can see pin numbers being printed on notepad.
However when connected the locked phone (motog 1st gen (falcon) ) and try , I get error HID USB device not ready.
I connected the OTG cable on the locked phone and normal cable on nethunter phone (redmi note 3 (kenzo)
Any tips?

**Comment by urbanadventurer** [comment]
Try this:
- reboot both devices
- unplug and replug the cables
- try using a real keyboard on the locked phone

**Comment by simtcrom** [comment]
I tried a real keyboard on the locked and it works.
Observation is, when I connect both phones each other, The battery icon on the nethunter phone is keep blinking between charging icon and normal. As if the power connected and disconnected loop.

I replaced motog with another locked phone (nexus 5) and no error any more, script started attempting pins.
Something to do with motog probably.

**Comment by urbanadventurer** [comment]
Thanks interesting. What is the full description of the Moto G so I can update the wiki and report it as not supported?

**Comment by simtcrom** [comment]
> Thanks interesting. Can you tell me more about this phone so I can list it as unsupported on the wiki?
> 
> https://github.com/urbanadventurer/Android-PIN-Bruteforce/wiki/Phone-Database

https://en.wikipedia.org/wiki/Moto_G_(1st_generation)

**Comment by urbanadventurer** [comment]
Could you help me fill in this table?


## List of unsupported phones

| Make         | Model       | Release year  | Android Version   | Tested by      | Config options          |
|--------------|-------------|---------------|-------------------|----------------|-------------------------|
| HTC          | One M8      | 2014          | 5.01              | @v1adf         |                         |
| LG           | K20         | 2019          | 9.0               | @v1adf         |                         |
| LG           | Q6          | 2017          | 8.01              | @v1adf         |                         |
| Motorola     | E6          | 2019          | 9.0               | @v1adf         |                         |
| Samsung      | A50         | 2019          | 10.0              | @v1adf         |                         |
| Samsung      | S7 Edge     | 2016          | 6.0.1             | @v1adf         |                         |
| Samsung      | S8          | 2017          | 9.0               | @v1adf         |                         |

**Comment by simtcrom** [comment]
> Could you help me fill in this table?
> 
> ## List of unsupported phones
> Make	Model	Release year	Android Version	Tested by	Config options
> HTC	One M8	2014	5.01	@v1adf	
> LG	K20	2019	9.0	@v1adf	
> LG	Q6	2017	8.01	@v1adf	
> Motorola	E6	2019	9.0	@v1adf	
> Samsung	A50	2019	10.0	@v1adf	
> Samsung	S7 Edge	2016	6.0.1	@v1adf	
> Samsung	S8	2017	9.0	@v1adf

Done at https://github.com/urbanadventurer/Android-PIN-Bruteforce/wiki/Phone-Database
