### ISSUE TITLE
./android-pin-bruteforce: config.default: line 24: syntax error: unexpected "("

### ISSUE THREAD

**Issue by bluegizmo83** [urbanadventurer/Android-PIN-Bruteforce#28]
./android-pin-bruteforce: config.default: line 24: syntax error: unexpected "("

I get this error when trying to run the script. I double checked and my config files were not modified and match this github exactly.

**Comment by bluegizmo83** [comment]
Nevermind! 

I was trying to launch the script from the AndroidSU terminal which is why it wasn't working. This script must be launched from the Kali terminal, then it works fine!

I'll leave this issue here so others can find it if they have the same issue, but it can be marked as resolved/closed.

**Comment by urbanadventurer** [comment]
I'll close it. People will still be able to Google this error.
