### ISSUE TITLE
Returned 127

### ISSUE THREAD

**Issue by HaroldLimad** [urbanadventurer/Android-PIN-Bruteforce#3]
Any solution thanks
![Screenshot_20201109-000546389](https://user-images.githubusercontent.com/64943687/98502231-7f4cc400-221f-11eb-848a-f3f92c40a42d.jpg)

**Comment by urbanadventurer** [comment]
Hi @HaroldLimad

Let's try to figure this out for ou.

What make and model of phone do you have?

What version of NetHunter are you using?

Does it work if you connect NetHunter to your computer and try sending keys?

`echo h e l l o | /system/xbin/hid-keyboard /dev/hidg0 keyboard`

**Comment by HaroldLimad** [comment]
e connected to the computer and if it works normal

my device Xiaomi redmi note 7
![Screenshot_20201109-232442441](https://user-images.githubusercontent.com/64943687/98627686-c5b72700-22e2-11eb-9c1c-7c31ef3edb5e.jpg)

**Comment by urbanadventurer** [comment]
I don't really understand your answer.

Try using `/dev/hidg1` as the virtual keyboard device. You can edit it in the `config` file.

**Comment by Chotu75** [comment]
> Hi @HaroldLimad
> 
> Let's try to figure this out for ou.
> 
> What make and model of phone do you have?
> 
> What version of NetHunter are you using?
> 
> Does it work if you connect NetHunter to your computer and try sending keys?
> 
> `echo h e l l o | /system/xbin/hid-keyboard /dev/hidg0 keyboard`

hello.. i also have same problem.. if i type "echo h e l l o | /system/xbin/hid-keyboard /dev/hidg0 keyboard" it shows "no such file or directories"
but i manually went /system/xbin and i found 'hid-keyboard' there.. 
help me
![Screenshot_20210515-141401](https://user-images.githubusercontent.com/8396405/118354256-e14c0480-b587-11eb-9494-2367f1465245.jpg)
 :)

**Comment by SweetSophia** [comment]
I have the same problem. --dry-run is fine. Both HID Device and hid-keyboard executable PASS . But when plugged in a device it returns the 127 error as seen above by HaroldLimad.
