### ISSUE TITLE
Getting error in line 625 unexpected"(("

### ISSUE THREAD

**Issue by sudo-xda** [urbanadventurer/Android-PIN-Bruteforce#31]

**Comment by urbanadventurer** [comment]
I need more information than this.
What terminal are you using? Take a look at #28

**Comment by sudo-xda** [comment]
Sorry my bad .i fixed it its a issue with my system/bin. I fixed that.Thanks for quick response.

**Comment by sudo-xda** [comment]
Fixed

**Comment by urbanadventurer** [comment]
OK NP
