### ISSUE TITLE
without nethunter

### ISSUE THREAD

**Issue by aspiringpentester1** [urbanadventurer/Android-PIN-Bruteforce#33]
bruteforcing pin without nethunter?
just from kali only?

**Comment by urbanadventurer** [comment]
@aspiringpentester1 
See the answer in the README. 
https://github.com/urbanadventurer/Android-PIN-Bruteforce#why-cant-you-use-a-laptop

# Why can't you use a laptop?

This works from an Android phone because the USB ports are not bidirectional, unlike the ports on a laptop.

**Comment by aspiringpentester1** [comment]
sigh

**Comment by urbanadventurer** [comment]
I'll rewrite that answer to be clearer.
