### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by hadess** [urbanadventurer/Android-PIN-Bruteforce#35]
What license is this tool under? It seems that the NetHunter `hid-keyboard` module is [under the GNU GPL 2](https://gitlab.com/kalilinux/nethunter/apps/kali-nethunter-app/-/blob/a0237fd888cb9dc6f02719e6a908e3625ee63a84/LICENSE).

**Comment by urbanadventurer** [comment]
I'll probably select GPLv3 but I haven't decided yet. As this project's source code (Bash) is not combined with the source code from hid-keyboard (C), I'm not restricted to using GPL-2.

Do you want me to clarify the license for a specific reason?

**Comment by hadess** [comment]
Without a license, I'm not even allowed to distribute any changes I'd make to the code.

**Comment by urbanadventurer** [comment]
I (Andrew Horton) hereby grant you (@hadess) permission to modify and distribute the source code for Android-PIN-Bruteforce until 1/1/2030.

**Comment by hadess** [comment]
I'll make a note to delete my fork on that date then :rofl:
