### ISSUE TITLE
Will it also work with USB C Devices with Android?

### ISSUE THREAD

**Issue by marcinguy** [urbanadventurer/Android-PIN-Bruteforce#7]
locked phone: usb-c -> male usb-a
nethunter: otg cable male micro-b to female usb-a

Seems like it should, but asking here.

Thanks,

**Comment by urbanadventurer** [comment]
I think it should work too. Can you let me know how your testing goes?

**Comment by 0x300T** [comment]
> locked phone: usb-c -> male usb-a
> nethunter: otg cable male micro-b to female usb-a
> 
> Seems like it should, but asking here.
> 
> Thanks,

works fine
