### ISSUE TITLE
[FAIL] HID device (/dev/hidg0) not found

### ISSUE THREAD

**Issue by atom7890** [urbanadventurer/Android-PIN-Bruteforce#80]
┌──(kali㉿kali)-[~/Downloads/Android-PIN-Bruteforce-master]
└─$ ./android-pin-bruteforce crack -p optimised-pin-length-4.txt                                                                                                                                                                          1 ⨯
Android PIN brute-force :: version 0.1
[INFO] Loading user specified PIN list optimised-pin-length-4.txt for 4 digits
[INFO] PIN list contains 10000 PINs
[INFO] Checking environment
[FAIL] HID device (/dev/hidg0) not found

mobile model - xiaomi redmi k20 pro

**Comment by saidsaidouni** [comment]
Got the same issue

**Comment by urbanadventurer** [comment]
I'm going to delete this sorry. Can you please make a new issue with more information? I've set it up with a template to fill in.
