### ISSUE TITLE
Nethunter phone has USB-C and locked phone has USB-C

### ISSUE THREAD

**Issue by Nirkster** [urbanadventurer/Android-PIN-Bruteforce#81]
Both phones have USB-C ports. Can I connect them with a simple USB-C to USB-C cable or do I have to go the USB-C -> OTG Cable -> USB-C route?

**Comment by urbanadventurer** [comment]
I think you will still need an OTG cable but test it anyway and let me know how it goes.

**Comment by Jordansemci** [comment]
Hello can u plis help me the scripts for installing Pin brute force
