### ISSUE TITLE
Locked phone: Xiaomi, Nethunter phone: nexus 6 - Bug description

### ISSUE THREAD

**Issue by k05tuni0** [urbanadventurer/Android-PIN-Bruteforce#95]
I launched the application, but my Xiaomi phone requires pressing the 'windows' key (winkey, GUI) to display the pin screen - I did not find another key combination. Is it possible to send the 'windows' key to my phone?

**Comment by k05tuni0** [comment]
left-meta

**Comment by urbanadventurer** [comment]
That's great that you found it. I hope you will share your config with everyone.
